steps:

  # Install node packages
  - name: "gcr.io/cloud-builders/npm:latest"
    args: ["install"]
    dir: "angular-on-gcp"

  # Build production package
  - name: "gcr.io/cloud-builders/npm:latest"
    args: [run, ng, "--", "build", "--prod"]
    dir: "angular-on-gcp"
