steps:

# Install node packages
- name: node:10.16.3
  entrypoint: npm
  args: ['install']

# Build productive files
- name: node:10.16.3
  entrypoint: npm
  args: [ 'run', 'build', '--prod' ]
  
- name: "gcr.io/cloud-builders/gcloud"
  args:

    [

     "compute",

     "scp",

     "--recurse",

     "dist",

     "xyz:/var/",

     "--zone=us-central1-a",

   ]
